initial_pose:
  x: -4.976927854538806
  y: -3.8297576369390764
  yaw: 0.0
waypoints:
- position:
    x: -5.3608485653435505
    y: -8.56994523664629
    yaw: 0.0
- position:
    x: -5.053621718831498
    y: -14.7405691753607
    yaw: 0.0
- position:
    x: -5.197378846860308
    y: -24.3932115998121
    yaw: 0.0
